# Generated by Django 5.2 on 2025-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_responsavel', models.CharField(help_text='Nome do curso responsável pelo evento', max_length=200, verbose_name='Curso responsável')),
                ('titulo', models.CharField(help_text='Título do evento', max_length=200, verbose_name='Título do evento')),
                ('tema', models.CharField(help_text='Tema principal do evento', max_length=200)),
                ('data', models.DateTimeField(help_text='Data e hora do evento', verbose_name='Data do evento')),
                ('descricao', models.TextField(help_text='Descrição detalhada do evento', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
