# Generated by Django 5.2 on 2025-05-01 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Selecione uma imagem', upload_to='eventos/imagens/%Y/%m/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, help_text='Descrição opcional da imagem', max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['ordem'],
            },
        ),
    ]
