# Generated by Django 5.2 on 2025-05-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_imagemevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='', help_text='Endereço ou local onde será realizado o evento', max_length=200, verbose_name='Local do evento'),
            preserve_default=False,
        ),
    ]
