# Generated by Django 5.2 on 2025-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('ocupacao', models.CharField(max_length=100, verbose_name='Ocupação')),
                ('coordenador', models.CharField(max_length=200, verbose_name='Coordenador(a)')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
