# Generated by Django 5.2 on 2025-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastro'},
        ),
        migrations.AddField(
            model_name='curso',
            name='contagem_iniciada',
            field=models.BooleanField(default=False, verbose_name='Contagem iniciada'),
        ),
    ]
