# Generated by Django 5.2 on 2025-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_curso_options_curso_contagem_iniciada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvidadoEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('formacao', models.CharField(max_length=200, verbose_name='Formação')),
                ('ocupacao', models.CharField(max_length=100, verbose_name='Ocupação')),
                ('recebeu_convite_de', models.CharField(max_length=200, verbose_name='Recebeu o convite de quem')),
                ('senha_especial', models.CharField(max_length=100, verbose_name='Senha especial')),
            ],
            options={
                'verbose_name': 'Convidado(a) Especial',
                'verbose_name_plural': 'Convidados(as) Especiais',
            },
        ),
        migrations.CreateModel(
            name='PublicoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('ocupacao', models.CharField(max_length=100, verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Público Geral',
                'verbose_name_plural': 'Público Geral',
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='contagem_iniciada',
        ),
    ]
