# Generated by Django 5.2 on 2025-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_convidadoespecial_publicogeral_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidadoespecial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
