# Generated by Django 5.2 on 2025-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_convidadoespecial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicogeral',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
