# Generated by Django 5.2 on 2025-05-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_curso_nome_curso_alter_convidadoespecial_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDosCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.EmailField(max_length=254)),
                ('valor_doacao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cadastro dos Cursos',
                'verbose_name_plural': 'Cadastro dos Cursos',
            },
        ),
    ]
