# Generated by Django 5.2 on 2025-05-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_cadastrodoscursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrodoscursos',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='cadastrodoscursos',
            name='valor_doacao',
        ),
    ]
