# Generated by Django 5.2 on 2025-05-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_remove_cadastrodoscursos_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodoscursos',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade'),
        ),
    ]
