# Generated by Django 5.2 on 2025-05-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_cadastrodoscursos_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhaDeControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=100, unique=True, verbose_name='Senha de controle')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Senha de controle',
                'verbose_name_plural': 'Senhas de controle',
            },
        ),
    ]
