# Generated by Django 5.2 on 2025-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_senhadecontrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhadecontrole',
            name='vaga',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20, verbose_name='Vaga'),
        ),
    ]
