# Generated by Django 5.2 on 2025-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_senhadecontrole_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do limite')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor do limite')),
            ],
            options={
                'verbose_name': 'Limite',
                'verbose_name_plural': 'Limites',
            },
        ),
    ]
