# Generated by Django 5.2 on 2025-05-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_limite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Limite',
        ),
    ]
