# Generated by Django 5.2 on 2025-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_delete_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCursosID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor do limite')),
            ],
            options={
                'verbose_name': 'Limite cursos ID',
                'verbose_name_plural': 'Limite cursos ID',
            },
        ),
        migrations.CreateModel(
            name='LimitePublicoGeralID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor do limite')),
            ],
            options={
                'verbose_name': 'Limite público geral ID',
                'verbose_name_plural': 'Limite público geral ID',
            },
        ),
    ]
