# Generated by Django 5.2 on 2025-05-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_limitecursosid_limitepublicogeralid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodoscursos',
            name='coordenador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenador(a)'),
        ),
        migrations.AlterField(
            model_name='cadastrodoscursos',
            name='modalidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastrodoscursos',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
