# Generated by Django 5.2.14 on 2026-05-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0018_cadastrodoscursos_coordenador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convidadoespecial",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contato"
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Contato"),
        ),
        migrations.AlterField(
            model_name="publicogeral",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contato"
            ),
        ),
        migrations.CreateModel(
            name="Certificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("imagem_fundo", models.ImageField(upload_to="certificados/")),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("cursos", "Cursos"),
                            ("convidados", "Convidados Especiais"),
                            ("publico", "Público Geral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome_x", models.IntegerField(default=400)),
                ("nome_y", models.IntegerField(default=300)),
                ("nome_fonte", models.CharField(default="Arial", max_length=50)),
                ("nome_tamanho", models.IntegerField(default=12)),
                ("nome_cor", models.CharField(default="#000000", max_length=7)),
                ("matricula_x", models.IntegerField(default=400)),
                ("matricula_y", models.IntegerField(default=350)),
                ("matricula_fonte", models.CharField(default="Arial", max_length=50)),
                ("matricula_tamanho", models.IntegerField(default=12)),
                ("matricula_cor", models.CharField(default="#000000", max_length=7)),
                ("conclusao_x", models.IntegerField(default=400)),
                ("conclusao_y", models.IntegerField(default=400)),
                ("conclusao_fonte", models.CharField(default="Arial", max_length=50)),
                ("conclusao_tamanho", models.IntegerField(default=12)),
                ("conclusao_cor", models.CharField(default="#000000", max_length=7)),
                (
                    "conclusao_texto",
                    models.CharField(default="Concluiu o evento", max_length=200),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eventos.evento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificação",
                "verbose_name_plural": "Certificações",
            },
        ),
    ]
