# Generated by Django 5.2.14 on 2026-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0019_alter_convidadoespecial_email_alter_curso_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificacao",
            name="conclusao_alinhamento",
            field=models.CharField(
                choices=[
                    ("left", "Esquerda"),
                    ("center", "Centralizado"),
                    ("right", "Direita"),
                    ("justify", "Justificado"),
                ],
                default="left",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="certificacao",
            name="matricula_alinhamento",
            field=models.CharField(
                choices=[
                    ("left", "Esquerda"),
                    ("center", "Centralizado"),
                    ("right", "Direita"),
                    ("justify", "Justificado"),
                ],
                default="left",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="certificacao",
            name="nome_alinhamento",
            field=models.CharField(
                choices=[
                    ("left", "Esquerda"),
                    ("center", "Centralizado"),
                    ("right", "Direita"),
                    ("justify", "Justificado"),
                ],
                default="left",
                max_length=10,
            ),
        ),
    ]
