# Generated by Django 5.2.14 on 2026-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0020_certificacao_conclusao_alinhamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificacao",
            name="conclusao_largura",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="certificacao",
            name="matricula_largura",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="certificacao",
            name="nome_largura",
            field=models.IntegerField(default=300),
        ),
    ]
