# Generated by Django 5.2.14 on 2026-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0021_certificacao_conclusao_largura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convidadoespecial",
            name="email",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Contato"
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="email",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Contato"
            ),
        ),
        migrations.AlterField(
            model_name="publicogeral",
            name="email",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Contato"
            ),
        ),
    ]
