# Generated by Django 5.1.7 on 2025-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_pedido_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='qr_codes/', verbose_name='QR Code')),
                ('instrucoes', models.TextField(help_text='Instruções que aparecerão na página de pagamento', verbose_name='Instruções de Pagamento')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave PIX')),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
