# Generated by Django 5.1.7 on 2025-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_comprador_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cota_final',
            field=models.IntegerField(default=999, verbose_name='Cota Final'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cota_inicial',
            field=models.IntegerField(default=1, verbose_name='Cota Inicial'),
        ),
    ]
