# Generated by Django 5.1.7 on 2025-03-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produto_cota_final_produto_cota_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprovante',
            old_name='data_upload',
            new_name='data_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='loja.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_comprador',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=20),
        ),
    ]
