# Generated by Django 5.1.7 on 2025-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_data_upload_comprovante_data_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_CONFIRMACAO', 'Aguardando Confirmação'), ('PAGO', 'Pago'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_CONFIRMACAO', max_length=22),
        ),
    ]
