# Generated by Django 5.1.7 on 2025-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cota',
            field=models.IntegerField(verbose_name='Cota'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_comprador',
            field=models.CharField(max_length=100, verbose_name='Nome do Comprador'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('AGUARDANDO_CONFIRMACAO', 'Aguardando Confirmação'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
