# Generated by Django 5.1.7 on 2025-03-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_pedido_options_pedido_comprovante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comprovante',
        ),
    ]
