# Generated by Django 5.1.7 on 2025-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_remove_pedido_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_comprador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('AGUARDANDO_CONFIRMACAO', 'Aguardando Confirmação'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=25),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
