# Generated by Django 5.1.7 on 2025-04-01 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_pedido_ordem_alter_pedido_cota_alter_pedido_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField()),
                ('id_novo', models.IntegerField()),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('deletado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
