# Generated by Django 5.1.7 on 2025-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_historicoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
