# Generated by Django 5.1.7 on 2025-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_pedido_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('AGUARDANDO_CONFIRMACAO', 'Confirmação de Pagamento'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=25),
        ),
    ]
