# Generated by Django 5.1.7 on 2025-04-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=50, unique=True, verbose_name='Senha')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('moedas_disponiveis', models.IntegerField(default=0, verbose_name='Moedas Disponíveis')),
                ('moedas_usadas', models.IntegerField(default=0, verbose_name='Moedas Usadas')),
                ('data_uso', models.DateTimeField(blank=True, null=True, verbose_name='Data de Uso')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
