# Generated by Django 5.1.7 on 2025-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_alter_configuracaofusohorario_fuso_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaofusohorario',
            name='fuso_horario',
            field=models.CharField(choices=[('America/Porto_Velho', 'UTC-4 (Horário Padrão do Amazonas - AMT)'), ('America/Sao_Paulo', 'UTC-3 (Horário de Brasília - BRT)')], default='America/Porto_Velho', max_length=50, verbose_name='Fuso Horário'),
        ),
    ]
