# Generated by Django 5.1.7 on 2025-04-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_logacesso'),
        ('loja', '0020_configuracaofusohorario'),
    ]

    operations = [
    ]
