# Generated by Django 5.2 on 2025-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_merge_0016_logacesso_0020_configuracaofusohorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacesso',
            name='data_acesso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logacesso',
            name='moedas_disponiveis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logacesso',
            name='moedas_usadas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logacesso',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
